### ISSUE TITLE
Remove /tmp/bashflix contents when killed

### ISSUE THREAD

**Issue by steeph-k** [0zz4r/bashflix#15]
When the script is killed, the contents of /tmp/bashflix remain there. It would be cleaner to use trap to remove them since the end of the script will not always be reached.

**Comment by FriendlyGecko** [comment]
try issuing this `echo "trap \"rm -r /tmp/torrent-stream/*\" exit 0" >> /usr/local/bin/bashflix`
this should append a working solution

**Comment by 0zz4r** [comment]
Hey! Thanks for the suggestion.` /tmp/bashflix ` should only have small `.srt` files, so no worries there. I've added an option on peerflix to delete the downloaded file on exit. Commit: https://github.com/0zz4r/bashflix/commit/aa7c5dfe80254b89cdf6b8300b5662cc5acf0b6b
