### ISSUE TITLE
Allow to seed after ending

### ISSUE THREAD

**Issue by steeph-k** [0zz4r/bashflix#17]
Not sure if this is easily implemented. But torrents shouldn't be seeded only as long as it takes to download ow watch the files. With most asynchronous internet connections this is not enough to even seed as much as was leeched. It would be nice to have an option that lets the script run after closing VLC so the torrent can at least be seeded until the user decided to end the script. Even better would be to have the torrent added to an already running transmission server instead of using peerflix. But I understand that this is not the purpose of the script.

**Comment by 0zz4r** [comment]
Thanks for the suggestion! Now it only stops seeding if the user closes the terminal. Commit:
https://github.com/0zz4r/bashflix/commit/4b8cb36cbd01eb9fb5d82f45a3bce0d5effa0ef7
