### ISSUE TITLE
opening multiple vlc instances at once

### ISSUE THREAD

**Issue by raiden076** [0zz4r/bashflix#24]
Hi again,
After selecting the movie, or even just playing with
bashflix "lord of the rings the two towers 1080p" en
it is opening multiple sometimes 3, sometimes even more,
and if i close any one of them,
all the others are closed as well.

**Comment by 0zz4r** [comment]
Hello! Thanks for reporting the issue.
I was not able to replicate the issue. I did some changes on bashflix so please run `bashflix update` and check again that query.

**Comment by raiden076** [comment]
I haven't faced the issue again,
Though changed the player to mpv soon after that, and it was good for me,
thanks for the response by the way..
